# ProjectX Automated Trading System Settings

# API settings
api:
  url: https://api.topstepx.com
  rtc_market_url: https://rtc.topstepx.com/hubs/market
  rtc_user_url: https://rtc.topstepx.com/hubs/user

# Database settings
database:
  # SQLite (default/fallback)
  url: sqlite:///projectx.db
  
  # TimescaleDB with PostgreSQL
  timescale_url: postgresql://postgres:password@localhost:5433/projectx
  use_timescale: true
  
  # Connection pool settings
  min_connections: 1
  max_connections: 10

# Timeframes to track (comma-separated)
# Available options: 1s, 5s, 15s, 30s, 1m, 5m, 15m, 30m, 1h, 2h, 4h, 1d, 1w, 1mo
timeframes:
  - 5m
  - 15m
  - 1h
  - 4h
  - 1d

# Logging settings
logging:
  level: "INFO"
  file_logging: true
  log_dir: "logs" 